import { ArrowUpRight, BriefcaseBusiness, Globe2, Plane } from "lucide-react";
import SectionHeading from "@/components/SectionHeading";

const projects = [
  { number: "01", title: "Travel booking platform", category: "TRAVEL · BOOKING", description: "A comprehensive travel technology platform designed to streamline flight, hotel, and bus bookings through a seamless and efficient workflow. Supports API integrations, booking management, and real-time travel data.", icon: Plane, tone: "project-blue" },
  { number: "02", title: "B2B booking application", category: "BUSINESS · BOOKING", description: "A business-focused booking application that enables travel agents, retailers, and distributors to manage flight, hotel, and bus bookings efficiently. Provides role-based access, product management, and streamlined booking operations.", icon: BriefcaseBusiness, tone: "project-cyan" },
  { number: "03", title: "B2C travel portal", category: "TRAVEL · CUSTOMER WEB", description: "A customer-facing travel portal that allows users to search, compare, and book flights, hotels, and other travel services online. Designed with a user-friendly interface to provide a smooth and convenient booking experience.", icon: Globe2, tone: "project-slate" },
];

export default function Projects() {
  return <section className="section projects-section" id="projects" aria-labelledby="projects-title"><div className="page-shell"><div className="projects-heading-row"><SectionHeading title="Projects & focus areas" titleId="projects-title" description="A glimpse at the kinds of products and workflows I work around." /><span className="project-note"><span /> PROJECT LINKS TO BE ADDED</span></div><div className="projects-grid">{projects.map(({ number, title, category, description, icon: Icon, tone }) => <article className="project-card" key={title}><div className={`project-visual ${tone}`}><div className="project-visual-grid" /><span className="project-number">{number}</span><div className="project-emblem"><Icon size={30} strokeWidth={1.4} /></div><span className="project-visual-coordinates">AS / {number}</span></div><div className="project-info"><p className="project-category">{category}</p><h3>{title}</h3><p className="project-description">{description}</p></div></article>)}</div><p className="projects-footnote">Project descriptions and external links will be added once details are confirmed.</p></div></section>;
}